### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by imlonghao** [Ciphey/CipheyDists#3]
Hello,

I am working on https://github.com/Ciphey/Ciphey/issues/137, may I know the license for the currently project? 
https://pypi.org/project/cipheydists/

Regrads,
imlonghao

**Comment by bee-san** [comment]
Hey imlonghao!!

Everything under Ciphey is MIT :D

**Comment by imlonghao** [comment]
How about create one now?

**Comment by bee-san** [comment]
Licenses have been added :)

**Comment by Cyclic3** [comment]
I'm gonna relicense this stuff as Unlicense, as I cannot really claim any content as my own (all of it is either public knowlege, or analysis of other people's works)
